/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_REGION: string
  readonly VITE_USER_POOL_ID: string
  readonly VITE_IDENTITY_POOL_ID: string
  readonly VITE_USER_POOL_CLIENT_ID: string
  readonly VITE_COGNITO_DOMAIN: string
  readonly VITE_COGNITO_JWKS_URL: string
  readonly VITE_ZERO_SERVER: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}